name = "Miniature Propulsion"
author = "tetrago"
version = "0.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2af2abe380574e8352d88e1f794e3ae18f8b17972c89978e3f8262873851a8bb"

[versions]
forge = "40.2.0"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.1"]
