name = "Minature Propulsion"
author = "tetrago"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7698c88d0bc8b499c3b86669410c977f866b11e117b1b45cca7a37da2792be7b"

[versions]
forge = "41.1.0"
minecraft = "1.19"
