name = "Miniature Propulsion"
author = "tetrago"
version = "0.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "24c826c2919ddbbc49482231e1e93bc2ae23a0a39627824ee98d6d5664837dfd"

[versions]
forge = "40.2.0"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.1"]
