name = "Minature Propulsion"
author = "tetrago"
version = "0.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "330ec2d9c6854cd7d8f3d576076a16d1c350558043c1c15118590a6e9340b453"

[versions]
forge = "40.2.0"
minecraft = "1.18.2"
