name = "Minature Propulsion"
author = "tetrago"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "411928d99e25cc5cc649ae4dcd98d7d9c287f22482739dd68dcc01b871bf0406"

[versions]
forge = "44.1.0"
minecraft = "1.19.2"
