name = "Miniature Propulsion"
author = "tetrago"
version = "0.6.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "08627f99e7ed1160dd01f3260c82fb1a8cc6c6daea8392f3425eabbcf0764afe"

[versions]
forge = "40.2.0"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.1"]
