name = "Minature Propulsion"
author = "tetrago"
version = "0.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ea6bb3e9683bd767dbebc851f6bd34ae41e205a72645fdd0c8a635091fb0aaf5"

[versions]
forge = "44.1.0"
minecraft = "1.19.3"
